import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";

import { Footer2 } from "@/components/footer2";

// import { TutorCard } from "./components/tutors/TutorCard";
import HelpCenterPro from "@/components/help1";
import LogosUltra from "@/components/logos3";
import FAQ from "./components/sections/faq";
import { Toaster } from "sonner";
import Navbar1 from "@/components/navbar1";
import FeaturedTutorsUltra from "@/components/feature17";
import UltraAttractivePage from "./allDetails/page";




const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "SkillBridge 🎓",
  // description: "Generated by create next app",
  description: "Connect with Expert Tutors, Learn Anything",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
        <Navbar1></Navbar1>
        
        {children}
        <Toaster richColors></Toaster>

        <FeaturedTutorsUltra></FeaturedTutorsUltra>

        {/* <TutorCard></TutorCard> */}

        <LogosUltra></LogosUltra>

        <FAQ></FAQ>

        <HelpCenterPro></HelpCenterPro>
        <UltraAttractivePage></UltraAttractivePage>

        <Footer2></Footer2>
      </body>
    </html>
  );
}
