import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import { Navbar1 } from "@/components/navbar1";
import { Footer2 } from "@/components/footer2";
import { FeaturedTutors } from "@/components/feature17";
import { TutorCard } from "./components/tutors/TutorCard";
import { HelpCenter } from "@/components/help1";
import { Logos3 } from "@/components/logos3";




const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "SkillBridge 🎓",
  // description: "Generated by create next app",
  description: "Connect with Expert Tutors, Learn Anything",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
        <Navbar1></Navbar1>
        
        {children}

        <FeaturedTutors></FeaturedTutors>

        <TutorCard></TutorCard>

        <Logos3></Logos3>

        <HelpCenter></HelpCenter>

        <Footer2></Footer2>
      </body>
    </html>
  );
}
